### ISSUE TITLE
Removed image

### ISSUE THREAD

**Issue by Eckankar** [treesnetwork/wdym#1]
https://i.imgur.com/UjrSTd9.gif has been removed from imgur, so the link is dead.

https://github.com/treesnetwork/wdym/blob/13a3502fbb3d93210dea9164701cf375ce97c814/src/imageCards.js#L96

**Comment by simonify** [comment]
Thanks for the report! Fixed in 53ff02782baa050ffdaf4bf8796ea62d92e0279f.
